# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_problemscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemscore',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
