# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_problemscore_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='question_text',
            new_name='problem_text',
        ),
    ]
