# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='history',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
