# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_auto_20161021_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='count',
            new_name='problem_count',
        ),
    ]
