# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_auto_20161021_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_history_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_problemscore_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
