# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcription', '0009_auto_20161023_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcription.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problemscore',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='problemscore',
            name='response_time_ms',
            field=models.IntegerField(null=True),
        ),
    ]
