# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0010_auto_20161028_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_packagestate_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
