# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedword',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Word'),
        ),
    ]
