# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20161026_0005'),
        ('vocabulary', '0003_auto_20161025_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Language')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Package')),
            ],
        ),
    ]
