# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_availablepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordstate',
            name='next_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
