# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0005_wordstate_next_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clearedpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='clearedpackage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClearedPackage',
        ),
    ]
