# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:43
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_auto_20161102_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordstate',
            name='next_date',
            field=models.DateField(default=core.utils.get_today),
        ),
    ]
