# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0011_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='n_state1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='n_state2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='n_state3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='n_state4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='n_state5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='n_state6',
            field=models.IntegerField(default=0),
        ),
    ]
