# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_text',
            field=models.CharField(max_length=30),
        ),
    ]
