# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161025_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_text',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.SmallIntegerField(default=20),
            preserve_default=False,
        ),
    ]
