# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
