# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20161031_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1990, 3, 7, 0, 0)),
            preserve_default=False,
        ),
    ]
