# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20161105_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_text',
            field=models.CharField(choices=[('ja', 'Japanese')], max_length=30, unique=True),
        ),
    ]
