# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_transcription', '0002_auto_20161014_0631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranscriptionGamePackage',
            new_name='Package',
        ),
        migrations.RenameModel(
            old_name='TranscriptionGameProblem',
            new_name='Problem',
        ),
    ]
